//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaNormal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devolucion
    {
        public int id_devolucion { get; set; }
        public Nullable<int> id_prestamo { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public System.DateTime fecha_devolucion_real { get; set; }
        public Nullable<decimal> multa { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
