//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaNormal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.Devolucion = new HashSet<Devolucion>();
        }
    
        public int id_prestamo { get; set; }
        public Nullable<int> id_lector { get; set; }
        public Nullable<int> id_libro { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public System.DateTime fecha_prestamo { get; set; }
        public System.DateTime fecha_devolucion_estimada { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Devolucion> Devolucion { get; set; }
        public virtual Lector Lector { get; set; }
        public virtual Libro Libro { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
